### ISSUE TITLE
npm package broken, missing dist folder

### ISSUE THREAD

**Issue by idmadj** [Khan/react-balance-text#3]
Mentioned this in PR #2, but adding in here to make it official since no action was taken in the last week or so.

Just got around to integrate 2.0.0 to a project. It looks like package.json refers to "main": "dist/index.js" ([permalink](https://github.com/Khan/react-balance-text/blob/67e4bb2d4172bc9ca74b59deb85795a0abfd53dd/package.json#L51)), but the NPM release is missing the dist folder.

See https://registry.npmjs.org/react-balance-text/-/react-balance-text-2.0.0.tgz

1.2.0 had it:
https://registry.npmjs.org/react-balance-text/-/react-balance-text-1.2.0.tgz

.npmignore looks fine.

**Comment by tage** [comment]
Is there a recommended way around this? Or plans to fix the npm issue?

**Comment by idmadj** [comment]
> Is there a recommended way around this? Or plans to fix the npm issue?

You can install from Github (and switch back to npm when this is fixed):

`npm install --save Khan/react-balance-text`
or 
`npm install --save https://github.com/Khan/react-balance-text/tarball/master`

**Comment by BrianGenisio** [comment]
The problem is that if you call `npm publish` on this repo without calling `npm install` first, the failure to compile will not be "noisy" enough to fail the `publish` command.  I've updated the prepublish script to fail more loudly if the compilation step fails so this problem won't happen again in the future.

**Comment by pmarcelll** [comment]
@BrianGenisio thank you, I appreciate the fast response.
I think this issue can be closed now.

**Comment by BrianGenisio** [comment]
Wonderful!  Thank you :)
